topcoder-platform/work-manager

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js, src/components/ChallengeEditor/index.js, src/util/date.js
=> #175 Fix up the Gantt charts

package-lock.json, public/index.html, src/actions/sidebar.js, src/components/Sidebar/Sidebar.module.scss, src/components/Sidebar/index.js, src/containers/Challenges/Challenges.module.scss, src/containers/Challenges/index.js, src/containers/Sidebar/index.js, src/containers/TopbarContainer/index.js, src/reducers/sidebar.js, src/routes.js
feat: git#669 project search improvements - allows search by id and exact phrase (to enable searching projects by title)
feat: git#669 project search improvements - moved the project search from left panel to main content area to have sufficient space to locate the project
feat: git#669 project search improvements - allows searching non my projects as well to support admin users (e.g. support team) to locate other projects/challenges
fix: minor style fix for the left panel
=> Project search improvements

src/components/ChallengeEditor/index.js
just pass the legacy object as it is coming from the GET response, with updates (if any that user makes - I guess only reviewType is the only thing that can be changed)
Additionally, small improvement to better handle null pointer w.r.t the current template
=> fix: git#740 - Can not activate challenge

src/actions/members.js, src/components/ChallengeEditor/AssignedMember-Field/AssignedMember-Field.module.scss, src/components/ChallengeEditor/AssignedMember-Field/index.js, src/components/ChallengeEditor/ChallengeView/index.js, src/components/ChallengeEditor/index.js, src/components/SelectUserAutocomplete/index.js, src/config/constants.js, src/containers/ChallengeEditor/index.js, src/reducers/index.js, src/reducers/members.js, src/services/user.js
- Autocomplete implemented as an independent and reusable component based on `react-select`.
- Action `loadMemberDetails` can be used to load details about any user by `userId`. It stores data in Redux Store `members` path. So this functionality could be reused to show handle for any other user by `userId`. 
- Potentially, this functionality could be converted to a single reusable hook so we don't have to pass `members` from the store everywhere where we need user details, but I guess we would have to update React `16.7` to `16.8.3+` together with `react-redux` from `6` till `7.1+` for this.
=> feat: field to assign a member to a task

src/components/ChallengeEditor/index.js, src/components/Modal/AlertModal.js, src/components/Modal/ConfirmationModal.js
ref issue #693
- Button to close the task added to the edit page, but not the list, as confirmed by Vikas https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-677504044
- `Close Task` button is only showed **after** the challenge is activated as clarified by Vikas https://github.com/topcoder-platform/challenge-engine-ui/issues/693#issuecomment-676348881
- As not all the fields which are needed to close a task are required in the form, I've added an error message which asks user to fill all the fields for closing task:
- If all required info is there and user clicks `Close Task` button, there is a confirmation dialog:
- If user clicks `Confirm` form is being processed and a standard successful message is showing:
Though at the moment when I'm trying to close the …
=> feat: closing task

src/components/Buttons/PrimaryButton/PrimaryButton.module.scss, src/components/Buttons/PrimaryButton/index.js, src/components/ChallengeEditor/FinalDeliverables-Field/FinalDeliverables-Field.module.scss, src/components/ChallengeEditor/FinalDeliverables-Field/index.js, src/components/ChallengeEditor/TextEditor-Field/index.js, src/components/ChallengeEditor/index.js
=> feat: editing final deliverables

.circleci/config.yml, src/components/ChallengeEditor/index.js, src/config/constants.js, src/containers/ChallengeEditor/index.js, src/services/challenges.js, src/util/tc.js
allowing admins to access challenge they don't directly belong to
fetching only default challenge timelines
=> Moving latest to prod

.gitignore, config/constants/production.js, src/components/ChallengeEditor/ChallengeView/index.js
Added a forum link from the view page as well as updating the production challenge terms UUID
=> Forum Link & New Terms ID

src/components/ChallengesComponent/ChallengesComponent.module.scss, src/components/ChallengesComponent/index.js
=> feat: show link to Direct project

src/components/ChallengeEditor/ChallengePrizes-Field/index.js, src/config/constants.js
=> feat: f2f should have only one prize

src/components/ChallengeEditor/TextEditor-Field/index.js
as per https://github.com/topcoder-platform/challenge-engine-ui/issues/880
=> feat: enabled private description

src/components/ChallengeEditor/ChallengeView/ChallengeView.module.scss, src/components/ChallengeEditor/ChallengeView/index.js, src/config/constants.js, src/containers/ChallengeEditor/index.js
— Added intelligent close task button which enables only when task is active and has assigned member.
=> feat: git#944-Move "Close Task" to View Screen

src/components/ChallengeEditor/ChallengeEditor.module.scss, src/components/ChallengeEditor/index.js
=> fix: show links for unsigned terms error

src/actions/challenges.js, src/components/ChallengesComponent/ChallengeCard/index.js, src/components/ChallengesComponent/ChallengeList/index.js, src/components/ChallengesComponent/index.js, src/containers/ChallengeEditor/index.js, src/containers/Challenges/index.js
=> fix: Challenge activation issues #993

config/constants/development.js, src/actions/challenges.js, src/components/ChallengeEditor/ReviewType-Field/index.js, src/components/ChallengeEditor/TextEditor-Field/index.js, src/components/ChallengeEditor/index.js, src/components/ChallengesComponent/ChallengeCard/index.js, src/components/ChallengesComponent/ChallengeList/index.js, src/components/ChallengesComponent/index.js, src/config/constants.js, src/containers/ChallengeEditor/index.js, src/containers/Challenges/index.js
https://github.com/topcoder-platform/work-manager/issues/995
More bug fixes around stale UI and error handling https://github.com/topcoder-platform/work-manager/issues/993
=> Prod Update - Disabled review type option for Design challenges

src/actions/challenges.js, src/components/ChallengeEditor/ChallengeView/index.js, src/services/challenges.js
=> fix:issue-986

src/components/ChallengeEditor/ChallengeView/index.js, src/components/ChallengeEditor/index.js
until challenge API is pushed to PROD
=> [HOTFIX] [PROD] Hide attachments

src/components/ChallengeEditor/ChallengeView/index.js, src/components/ChallengeEditor/NDAField/NDAField.module.scss, src/components/ChallengeEditor/NDAField/index.js, src/components/ChallengeEditor/Terms-Field/index.js, src/components/ChallengeEditor/index.js
=> add default terms and refractor nda input

src/components/ChallengeEditor/index.js, src/containers/ChallengeEditor/index.js
=> fix project terms load and default terms in beta

src/components/ChallengeEditor/ChallengeTotal-Field/index.js, src/components/ChallengeEditor/ChallengeView/index.js, src/components/ChallengeEditor/index.js, src/util/input-check.js
Final release for Project Defaults Shape up project.
=> Prod Release - 0.5.2

src/components/ChallengeEditor/ChallengeViewTabs/index.js, src/components/ChallengesComponent/ChallengeCard/index.js, src/components/ChallengesComponent/ChallengeList/index.js, src/components/ChallengesComponent/ChallengeStatus/index.js
added approved challenges tab
updated canLaunch comment to reflect updated rules
=> Self Service App -- approved challenges tab

src/components/ChallengeEditor/ChallengeViewTabs/index.js, src/components/ChallengeEditor/index.js, src/containers/ChallengeEditor/index.js
=> Prod release

.circleci/config.yml, src/components/ChallengeEditor/ChallengeViewTabs/index.js, src/components/ChallengesComponent/ChallengeList/ChallengeList.module.scss, src/components/ChallengesComponent/ChallengeList/index.js, src/components/ChallengesComponent/index.js, src/containers/Challenges/index.js, src/reducers/projects.js
Adding billing account start / end dates
=> Billing account start / end date additions

src/components/ChallengeEditor/index.js
https://topcoder.atlassian.net/browse/PROD-2823
=> Add QA tag for QA challenges

src/components/ChallengeEditor/ChallengeViewTabs/index.js, src/components/ChallengeEditor/Submissions/index.js, src/components/ChallengeEditor/index.js, src/config/constants.js, src/util/tc.js, src/util/topcoder-react-lib.js
Stop copilots from paying themselves (in the UI): https://topcoder.atlassian.net/browse/PROD-4364
WM is not handling error response from submissions-api download endpoint
https://topcoder.atlassian.net/browse/PROD-4355
=> Sept 2023 release

config/constants/development.js, config/constants/production.js, src/actions/challenges.js, src/config/constants.js, src/services/challenges.js
https://topcoder.atlassian.net/browse/TSJR-284
=> Update the URL for saving skills

.circleci/config.yml, build.sh, src/components/ChallengeEditor/index.js
https://topcoder.atlassian.net/browse/CORE-396
=> PROD - Support dashboard checkbox for code challenges

src/components/ChallengeEditor/ChallengeView/index.js, src/components/ChallengeEditor/index.js, src/components/ChallengesComponent/index.js, src/components/ProjectCard/index.js
https://topcoder.atlassian.net/browse/PM-226
- Replaces the `dangerouslySetInnerhtml` with explicit plaintext render
=> PM-226 Fix React bad practice: dangerouslySetInnerhtml

config/env.js, config/paths.js, config/webpack.config.js, scripts/build.js, scripts/start.js
https://topcoder.atlassian.net/browse/PM-218
Fix DOS vulnerability by removing checks at places
=> PM-218 Fix DOS issues with fs

src/components/ProjectForm/GroupsFormField/index.js, src/components/ProjectForm/GroupsFormField/use-map-selected-groups.hook.js, src/components/ProjectForm/ProjectForm.module.scss, src/components/ProjectForm/index.js
https://topcoder.atlassian.net/browse/PM-686 - added NDA & Work groups fields for the edit project form.
Note that I did not use `ChallengeEditor\Groups-Field` as it was implemented too specific for the challenge form. But I did reuse all the utility functions (services) to fetch groups & group details.
=> PM-686 - NDA & work groups for projects

src/actions/projects.js, src/actions/sidebar.js, src/components/ProjectCard/index.js, src/config/constants.js, src/containers/Challenges/index.js, src/containers/Projects/index.js, src/containers/Projects/styles.module.scss, src/containers/TaaSList/index.js, src/containers/Tab/index.js, src/reducers/projects.js, src/reducers/sidebar.js, src/routes.js
https://topcoder.atlassian.net/browse/PM-875 - WM: Filters/Search for 'Projects'
- move projects page to a new container. It was part of challenges container, but didn't make sense. Also the need to add filters/search was making the challenges container too complex
- added search & status filters on projects page
- updated & added infinite scoll to TaaS as well
=> PM-875 - move projects to new container, add filters

src/components/ChallengesComponent/ChallengeList/index.js
The challenge list fetch endpoint was being passed with the previous project Id selected. In case of reset Filter, projectId should be changed to undefined(?)
=> PM-898 Fix reset filter in Challenge listing

src/components/ChallengeEditor/ChallengeView/index.js
Adds link to project overview page on the Challenge View page where Project name is mentioned.
=> PM-903 Add project link to challenge view

src/components/ChallengeEditor/ArtifactsListModal/ArtifactsListModal.module.scss, src/components/ChallengeEditor/ArtifactsListModal/index.js, src/components/ChallengeEditor/Submissions/index.js, src/components/Tooltip/index.js
- Added a functionality in tooltip to remove the tooltip on click of the trigger elememt
- Added "No artifacts found" text when no artifacts are available in the challenge
=> fix(PM-810): tooltip and added empty content text

src/actions/projects.js, src/config/constants.js, src/containers/Projects/index.js, src/containers/Projects/styles.module.scss, src/util/tc.js
- Allow project managers to view all projects
- Added a checkbox to show only my projects
=> fix(PM-974) Allow project managers to view all projects

src/actions/challenges.js, src/actions/sidebar.js, src/actions/users.js, src/components/Users/index.js, src/containers/Projects/index.js, src/containers/Users/index.js, src/reducers/users.js
- Allow Project Managers to view users from project which are not assigned to them
- This will also give permission to PMs to add new user and remove user from other projects
=> feat(PM-974): allow PM to view users and delete users from project

src/containers/ProjectInvitations/index.js, src/util/delay.js
- Added delay fn to make code more concise
- await for project updates propagation before redirecting
=> PM-973 - invite by email - fix awaiting for project updates to propagate

config/constants/development.js, config/constants/production.js, src/components/Users/index.js, src/components/Users/invite-user.modal.js, src/components/Users/user-add.modal.js, src/config/constants.js, src/containers/Users/index.js, src/services/projects.js
- Copilot invitation with email flow
=> feat(PM-972): copilot invitation with email

src/components/ChallengesComponent/ChallengeList/index.js, src/components/UpdateBillingAccount/index.js
- show update/add billing address for project manager who belongs to the project
=> fix(PM-574): show update/add billing address for project manager who belongs to the project

src/components/ChallengesComponent/ChallengeList/index.js, src/components/UpdateBillingAccount/index.js
- Cherry picked the PM-1093 from develop.
- https://topcoder.atlassian.net/browse/PM-1093
-
=> [PROD RELEASE] - release pm1093

src/components/ProjectCard/index.js, src/config/constants.js
- Fixed broken search in projects list
- Ticket link - https://topcoder.atlassian.net/browse/PM-1137
=> fix(PM-1137): search broken in projects list

src/components/Users/index.js, src/containers/Users/index.js
- Show spinner when changing between projects
- Ticket link - https://topcoder.atlassian.net/browse/PM-1140
=> fix(PM-1140): show spinner when changing between projects

src/components/UserCard/index.js, src/components/Users/index.js, src/containers/Users/index.js
https://topcoder.atlassian.net/browse/PM-1137
https://topcoder.atlassian.net/browse/PM-1140
=> [PROD RELEASE] - Bug fixes

src/components/ChallengesComponent/index.js
- show request copilot for PMs
=> fix(PM-1317): show request copilot for PMs

.circleci/config.yml, src/routes.js
- Retain query param in invite link
=> fix(PM-1355): Retain query param in invite link

src/components/Users/Users.module.scss, src/components/Users/index.js, src/components/Users/user-add.modal.js, src/services/projects.js
- Overwrite role if the copilot is already a member of the project with "read"/"write" access
Ticket link - https://topcoder.atlassian.net/browse/PM-1506
=> feat(PM-1506): Overwrite role if the copilot is already a member of the project with "read"/"write" access

.circleci/config.yml, src/components/ChallengesComponent/index.js
- added projectId query param to request form url
Ticket link - https://topcoder.atlassian.net/browse/PM-1365
=> fix(PM-1365): added projectId query param to request form url
