topcoder-platform/work-manager

src/components/CreateNewChallenge/CreateNewChallenge.module.scss
src/components/CreateNewChallenge/index.js
src/components/Sidebar/Sidebar.module.scss
src/components/TwoColsLayout/TwoColsLayout.module.scss

fix for jumping content panel

---

src/components/CreateNewChallenge/index.js

Fix for issues#53

---

src/components/CreateNewChallenge/ChallengePrizes-Field/index.js
src/components/CreateNewChallenge/index.js

Fixed challenge prizes section

Fixed issues#54

---

src/components/ProjectCard/ProjectCard.module.scss

Remove a:last-child in Project Card. It was not being used

Fix issue #69

---

src/components/ChallengesComponent/ChallengeCard/index.js
src/components/ChallengesComponent/ChallengeTag/ChallengeTag.module.scss
src/components/ChallengesComponent/ChallengeTag/index.js

Show challenge tag in challenge cards

---

src/actions/challenges.js
src/components/ChallengeEditor/BillingAccount-Field/index.js
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/Copilot-Field/index.js
src/components/ChallengeEditor/Groups-Field/index.js
src/components/ChallengeEditor/ReviewType-Field/index.js
src/components/ChallengeEditor/TagsField/index.js
src/components/ChallengeEditor/Terms-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/Type-Field/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/index.js
src/config/constants.js

Performance fixes for challenge listings and editor

---

src/components/ChallengeEditor/index.js

Reset duration on template change

---

package.json
src/components/ChallengeEditor/Attachment-Field/Attachment-Field.module.scss
src/components/ChallengeEditor/Attachment-Field/index.js
src/components/ChallengeEditor/index.js

#80 Support auto-save + #129 Attachment panel fixes

#80 Support auto-save + #129 Attachment panel fixes

---

config/constants/development.js
config/constants/production.js
src/components/ChallengesComponent/ChallengesComponent.module.scss
src/components/ChallengesComponent/index.js
src/config/constants.js

#147 Add "View Project in Connect" button to project page

#147 Add "View Project in Connect" button to project page

---

src/components/ChallengesComponent/index.js

#147 open up a new window / tab

#147 open up a new window / tab

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/services/challenges.js
src/util/date.js

Fix issue 162, Gantt chart not displaying properly.

Fix issue 162, Gantt chart not displaying properly.

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/ReviewType-Field/index.js
src/components/ChallengeEditor/Track-Field/index.js
src/components/ChallengeEditor/index.js
src/services/challenges.js
src/util/date.js

#166 Broken challenge launching

#166 Broken challenge launching

---

src/components/ChallengeEditor/index.js

#166 fix conflict undefined track + preview type

#166 fix conflict undefined track + preview type

---

src/components/ChallengesComponent/index.js

#170 Remove buttons from `Active Challenges` tab

#170 Remove buttons from `Active Challenges` tab

---

src/actions/challenges.js
src/containers/Challenges/index.js
src/reducers/challenges.js

#171 fix load challenge after change project id

#171 fix load challenge after change project id

---

src/components/ChallengesComponent/ChallengeCard/index.js
src/components/ChallengesComponent/ChallengeList/index.js

#172 Remove Current Phase from specific tabs

#172 Remove Current Phase from specific tabs

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js

#175 phase duration is hours

---

src/actions/sidebar.js

#183 Update project search

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js

#188 Updates to gantt chart on create challenge page

#188 Updates to gantt chart on create challenge page

---

src/actions/challenges.js

#193 Apply sorting to challenge listings

#193 Apply sorting to challenge listings

---

src/components/ChallengesComponent/ChallengeCard/index.js
src/components/ChallengesComponent/ChallengeList/index.js
src/components/ChallengesComponent/ChallengeStatus/ChallengeStatus.module.scss
src/components/ChallengesComponent/ChallengeStatus/index.js
src/config/constants.js
src/styles/_colors.scss

Add 'New' status tag to homepage.

Add 'New' status tag to homepage.

---

src/components/ChallengeEditor/index.js
src/services/challenges.js
src/util/date.js

#189 Date selection

---

src/components/ChallengeEditor/index.js

#214 Send timelineTemplateId along with phase information

#214 Send timelineTemplateId along with phase information

---

src/components/ChallengeEditor/index.js

#214 timelineTemplateId value, but the dropdown remains un-populated

#214 timelineTemplateId value, but the dropdown remains un-populated

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/index.js

#218 Gantt chart not loading properly after timeline template is applied

#218 Gantt chart not loading properly after timeline template is applied

---

src/services/challenges.js

#223 Change to show schedule as hours not reflecting

#223 Change to show schedule as hours not reflecting

---

src/components/ChallengeEditor/index.js

Fix issue 221. Field validation not working.

Fix issue 221. Field validation not working.

---

src/components/ChallengeEditor/index.js

#229 Move "Type" to first page of challenge creation

#229 Move "Type" to first page of challenge creation

---

src/components/ChallengeEditor/ReviewType-Field/index.js
src/components/ChallengeEditor/Track-Field/index.js
src/components/ChallengeEditor/Type-Field/index.js
src/components/ChallengeEditor/index.js
src/components/Track/Track.module.scss
src/components/Track/index.js

#230 Better disabled state for Track and Type + #232 Launch as Draft cleanup

#230 Better disabled state for Track and Type + #232 Launch as Draft cleanup

---

src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js

#232 Launch as Draft cleanup + #235 Specifications not loading after refresh

#232 Launch as Draft cleanup + #235 Specifications not loading after refresh

---

src/components/ChallengeEditor/ChallengeEditor.module.scss
src/components/ChallengeEditor/index.js
src/components/Track/Track.module.scss

#243 Change look and feel of Track and Type on challenge edit screen

#243 Change look and feel of Track and Type on challenge edit screen

---

src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/index.js

#244 Swap view and edit functionality on the table view
#245 Make `Community` review the default
#246 Hide attachment panel

Issue #244 #245 #246

---

src/components/ChallengeEditor/Description-Field/Description-Field.module.scss
src/components/ChallengeEditor/Description-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/TextEditor-Field.module.scss
src/components/ChallengeEditor/TextEditor-Field/index.js

#247 Private Specification tweak

#247 Private Specification tweak

---

src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/Track/Track.module.scss

#243 minor tweak
#247 minor tweak

#247 + #243 minor tweak

---

src/components/ChallengeEditor/index.js

#232 minor tweak

---

src/components/ChallengeEditor/index.js

#244 fix loading challenge problem

#244 fix loading challenge problem

---

src/components/ChallengeEditor/Description-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js

#239 Tweak auto-PATCH of specification fields

#239 Tweak auto-PATCH of specification fields

---

src/actions/challenges.js
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/Description-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js
src/services/challenges.js

#239 10 second PATCH
#260 PATCH requests stop after `Launch as Draft`
#238 remove the initial request with just the timelineTemplateId
#261 Gantt chart updates
#262 Update groups API call

PR for Issue #239 #260 #238 #261 #262

---

src/actions/challenges.js
src/actions/projects.js
src/containers/ChallengeEditor/index.js

#267 Project on challenge edit page

#267 Project on challenge edit page

---

src/actions/challenges.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js
src/components/PhaseInput/index.js

#265 UI Updates

---

src/components/ChallengeEditor/MaximumSubmissions-Field/index.js
src/components/ChallengeEditor/StockArts-Field/index.js
src/components/ChallengeEditor/SubmissionVisibility-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js

#236 Map design fields

---

src/components/ChallengeEditor/index.js

#236 fix limit/unlimit problem

#236 fix limit/unlimit problem

---

src/components/Buttons/PrimaryButton/PrimaryButton.module.scss
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/CopilotFee-Field/CopilotFee-Field.module.scss
src/components/ChallengeEditor/CopilotFee-Field/index.js
src/components/ChallengeEditor/MaximumSubmissions-Field/MaximumSubmissions-Field.module.scss
src/components/ChallengeEditor/index.js
src/containers/ChallengeEditor/index.js
src/reducers/challenges.js
src/styles/forms.scss

#596 Changes not always loading properly
#592 UI Cleanup

#596 Changes not always loading properly + #592 UI Cleanup

---

config/constants/development.js
config/constants/production.js
src/components/ChallengesComponent/ChallengeCard/ChallengeCard.module.scss
src/components/ChallengesComponent/ChallengeCard/index.js
src/config/constants.js

#564 Link to Direct & OR

---

src/containers/ChallengeEditor/index.js

#629 Investigate new challenge page not loading

#629 Investigate new challenge page not loading

---

src/components/Buttons/PrimaryButton/PrimaryButton.module.scss
src/components/ChallengeEditor/ChallengePrizes-Field/index.js
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/ReviewType-Field/ReviewType-Field.module.scss
src/components/ChallengeEditor/ReviewType-Field/index.js
src/components/ChallengeEditor/Terms-Field/Terms-Field.module.scss
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/index.js

#570 End Date/Time moves towards
#524 No error message on Select Reviewer if user tried to save the record
#517 Page content moves down when user go to next and previous pages via pagination
#502 Edit Challenge - No way to regain the deleted challenge phase (if deleted by mistake)
#487 Can't see the (*) marker for the Prize 
#468 Delete all not available in Terms

Issues #570 #524 #517 #502 #487 #468

---

src/components/ChallengeEditor/ChallengeEditor.module.scss
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/ChallengeCard.module.scss
src/components/ChallengesComponent/ChallengeCard/index.js

#448 Timeline is corrupted when user re-select the timeline template from the dropdown
#407 Click on the below and above "View Challenge" link will not trigger the edit challenge page
#555 Order of the phases are incorrect in Challenge creation process
#405 Error message is in correct, Description is not a required field

#448 Timeline is corrupted + #407 + #555 + #405

---

src/components/ChallengeEditor/ChallengeSchedule-Field/index.js

#502 Edit Challenge - No way to regain the deleted challenge

#502 Edit Challenge - No way to regain the deleted challenge

---

config/constants/development.js
config/constants/production.js
src/components/ChallengeEditor/NDAField/NDAField.module.scss
src/components/ChallengeEditor/NDAField/index.js
src/components/ChallengeEditor/index.js
src/config/constants.js

#264 Terms update

---

src/components/ChallengeEditor/index.js

#264 keep sending the default term

#264 keep sending the default term

---

src/components/ChallengeEditor/ChallengeSchedule-Field/ChallengeSchedule-Field.module.scss
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/index.js
src/components/ChallengesComponent/ChallengeList/ChallengeList.module.scss
src/components/ChallengesComponent/ChallengeList/index.js
src/components/ChallengesComponent/ChallengesComponent.module.scss
src/services/challenges.js

#647 Undefined legacyId
#646 Move Reset Phases
#491 While creating new challenge, Edit button under challenge schedule is not working
#420 Edit button collapse and expand ^ is same should be different

Fix Issues #647 #646 #491 #420

---

src/components/ChallengeEditor/MaximumSubmissions-Field/MaximumSubmissions-Field.module.scss
src/components/ChallengeEditor/MaximumSubmissions-Field/index.js
src/components/ChallengeEditor/StockArts-Field/StockArts-Field.module.scss
src/components/ChallengeEditor/StockArts-Field/index.js
src/components/ChallengeEditor/SubmissionVisibility-Field/SubmissionVisibility-Field.module.scss
src/components/ChallengeEditor/SubmissionVisibility-Field/index.js

#395 Unable to access Stock Arts and submission visibility checkbox using tab key

#395 Unable to access Stock Arts and submission visibility

---

src/components/ChallengesComponent/ChallengeCard/ChallengeCard.module.scss
src/components/ChallengesComponent/ChallengeCard/index.js
src/components/ChallengesComponent/ChallengeList/ChallengeList.module.scss
src/components/ChallengesComponent/ChallengeList/index.js
src/components/PhaseInput/index.js

#349 After activating the challenge from draft clicking on dialog's close button nothing is happening
#292 If the challenge name is big

#349 clicking on dialog's close button nothing is happening + #292 If the challenge name is big

---

src/components/ChallengeEditor/ChallengeSchedule-Field/ChallengeSchedule-Field.module.scss
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js

#646 Move Reset Phases

---

src/components/ChallengesComponent/ChallengeCard/index.js

#657 Update challenge link

---

src/components/ChallengeEditor/index.js

#658 Limit prizes

---

src/components/PhaseInput/index.js

Fix the issue with the ability to enter text or number in the start date input field.

Fix the issue with the ability to enter text or number in the start date input field.

---

package-lock.json
package.json
src/components/ChallengeEditor/Attachment-Field/index.js
src/components/ChallengeEditor/ChallengePrizes-Field/index.js
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/ChallengeView/ChallengeView.module.scss
src/components/ChallengeEditor/ChallengeView/index.js
src/components/ChallengeEditor/Copilot-Field/index.js
src/components/ChallengeEditor/CopilotFee-Field/index.js
src/components/ChallengeEditor/Description-Field/index.js
src/components/ChallengeEditor/FinalDeliverables-Field/FinalDeliverables-Field.module.scss
src/components/ChallengeEditor/FinalDeliverables-Field/index.js
src/components/ChallengeEditor/MaximumSubmissions-Field/index.js
src/components/ChallengeEditor/NDAField/NDAField.module.scss
src/components/ChallengeEditor/NDAField/index.js
src/components/ChallengeEditor/StockArts-Field/StockArts-Field.module.scss
src/components/ChallengeEditor/StockArts-Field/index.js
src/components/ChallengeEditor/SubmissionVisibility-Field/SubmissionVisibility-Field.module.scss
src/components/ChallengeEditor/SubmissionVisibility-Field/index.js
src/components/ChallengeEditor/TagsField/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/index.js
src/components/CopilotCard/index.js
src/components/PhaseInput/PhaseInput.module.scss
src/components/PhaseInput/index.js
src/components/PrizeInput/index.js
src/containers/ChallengeEditor/index.js
src/routes.js

#658 limiting the prize to 1000000
#659 Refactor flow

#658 limiting the prize to 1000000 + #659 Refactor flow

---

src/components/ChallengeEditor/ChallengeView/index.js
src/components/ChallengeEditor/index.js
src/containers/ChallengeEditor/index.js

#659 Two minor things

---

src/components/ChallengeEditor/FinalDeliverables-Field/FinalDeliverables-Field.module.scss
src/components/ChallengeEditor/FinalDeliverables-Field/index.js
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js

Add input field before 'Add File Type' button to allow user add new file type.

Add input field before 'Add File Type' button to allow user add new file type.

---

src/components/ChallengeEditor/AssignedMember-Field/index.js
src/components/SelectUserAutocomplete/index.js
src/containers/ChallengeEditor/index.js

small fixes after implementing #673 by PR https://github.com/topcoder-platform/challenge-engine-ui/pull/756
fyi @vikasrohit

Small fixes

---

src/components/ChallengeEditor/ChallengePrizes-Field/index.js

issue #691
For task only one prize is shown without number and without a button to add more prizes:
FYI @vikasrohit

feat: allow only one prize for task

---

src/reducers/challenges.js
src/services/challenges.js

#774 - fix: update challenge in the list after editing

---

src/components/ChallengeEditor/ChallengePrizes-Field/index.js
src/components/ChallengeEditor/index.js

#777 - fix: display prize error next to the field

---

src/components/ChallengeEditor/index.js

#779 - fix: basic validation for new challenge

---

src/actions/challenges.js
src/components/ChallengeEditor/LastSaved-Display/index.js
src/components/ChallengeEditor/index.js
src/containers/ChallengeEditor/index.js
src/services/challenges.js

Now `Last Saved` shows the actual `updated` field of the saved challenge. Fixing this also including putting updated challenge data to the redux store on auto save, otherwise an outdated date would be shown as `Last Saved` when challenge is saved automatically without pressing "Save" button.
ref issue #785

#785 - fix: 'Last Saved' Date and autosaving to redux

---

src/components/Buttons/OutlineButton/Outline.module.scss
src/components/Buttons/OutlineButton/index.js
src/components/ChallengeEditor/index.js

#680 - fix: creating multiple challenges at a time

---

src/components/ChallengeEditor/ChallengePrizes-Field/index.js

#779 - Part 2 - fix: don't show prize validation immediately

---

src/components/ChallengeEditor/FinalDeliverables-Field/index.js

fix: avoid duplicate final deliverable

---

src/components/ChallengeEditor/ChallengePrizes-Field/index.js
src/components/ChallengeEditor/CheckpointPrizes-Field/index.js
src/components/ChallengeEditor/CopilotFee-Field/index.js
src/components/ChallengeEditor/ReviewCost-Field/index.js
src/config/constants.js

fix: prizes object format

---

src/components/ChallengeEditor/TagsField/index.js
src/components/ChallengeEditor/index.js

https://github.com/topcoder-platform/challenge-engine-ui/issues/876
https://github.com/topcoder-platform/challenge-engine-ui/issues/848
https://github.com/topcoder-platform/challenge-engine-ui/issues/877

buttons for saving challenge in current status

---

src/containers/ChallengeEditor/index.js

We changed the model of the ResourceRole table to have `fullReadAccess` and `fullWriteAccess` so we need to change this as well
cc @rootelement

Change fullAccess to fullWriteAccess

---

.circleci/config.yml
config/constants/production.js
src/components/ChallengeEditor/index.js
src/util/tc.js

Fixing the NDA UUID
Adding a Forum Link to the View page
Changing the Resource Role association

Update NDA and Resource Roles

---

src/config/constants.js
src/services/challenges.js

fix: show all groups in dropdown

---

src/components/ChallengeEditor/ChallengeView/ChallengeView.module.scss
src/components/LegacyLinks/LegacyLinks.module.scss

fix: space between the buttons

---

src/components/ChallengeEditor/index.js

fix: remove 'Direct/Online Review' on Create New

---

src/components/ChallengeEditor/index.js

fix: validation of "tags"

---

src/components/Buttons/PrimaryButton/PrimaryButton.module.scss
src/components/ChallengeEditor/index.js
src/components/LegacyLinks/LegacyLinks.module.scss

- additionally fixed PrimaryButton styles globally not only for legacy links
ref issue #933

fix: disable "launch active" when no legacy

---

.gitignore
src/components/ChallengeEditor/ChallengeView/index.js
src/components/ChallengeEditor/index.js
src/containers/ChallengeEditor/index.js
src/util/tc.js

This contains fixes for 2 issues
- #914
- #913

Fix task assigning and closing issues

---

src/components/ChallengeEditor/ChallengeView/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/ChallengeCard.module.scss
src/components/ChallengesComponent/ChallengeCard/index.js
src/components/LegacyLinks/index.js
src/config/constants.js

fix: disable on the listing page without legacy

---

src/components/ChallengeEditor/index.js

fix: validate challenge before autosave

---

src/components/ChallengeEditor/TextEditor-Field/index.js

fix: public specification error above private

---

src/components/ChallengeEditor/index.js

[PROD] [HOTFIX] Missing terms

---

src/components/ChallengeEditor/Groups-Field/index.js

fix search group placeholder

---

src/components/ChallengeEditor/index.js

pass project groups to new challenge

---

src/components/ChallengeEditor/ChallengeEditor.module.scss
src/components/ChallengeEditor/TextEditor-Field/index.js
src/components/ChallengeEditor/index.js

fix: issue #1062

---

src/components/ChallengeEditor/ChallengeView/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeCard/index.js

Reverts topcoder-platform/work-manager#1076

Revert "Pure V5 task"

---

src/components/ChallengesComponent/ChallengeCard/ChallengeCard.module.scss
src/components/ChallengesComponent/ChallengeStatus/ChallengeStatus.module.scss
src/components/ChallengesComponent/ChallengeTag/ChallengeTag.module.scss

- Improved differentiation between tags and actionable buttons

fix: git#1129-Actionable affordances are inconsistent and confusing

---

src/components/ChallengeEditor/ChallengeEditor.module.scss
src/components/ChallengeEditor/ChallengeViewTabs/ChallengeViewTabs.module.scss
src/components/ChallengeEditor/ChallengeViewTabs/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeList/index.js
src/components/ChallengesComponent/ChallengesComponent.module.scss
src/components/LegacyLinks/LegacyLinks.module.scss
src/components/LegacyLinks/index.js
src/config/constants.js

Issue 1019

---

test-automation/config/app-config.json
test-automation/page-objects/create-challenge/create-challenge.helper.ts
test-automation/page-objects/create-challenge/create-challenge.model.ts
test-automation/page-objects/create-challenge/create-challenge.po.ts
test-automation/page-objects/dashboard/dashboard.helper.ts
test-automation/test-data/test-data.json
test-automation/test-suites/create-challenge-flow/create-challenge.spec.ts

Topcoder Work Manager - E2E Test Automation - Random test fails version 1.0

Fixed issues for Challenge

---

.circleci/config.yml
src/components/Modal/ConfirmationModal.js

https://github.com/topcoder-platform/legacy-payment-processor/issues/12

Prod Release - resolve multiple clicks response when closing a challenge

---

.circleci/config.yml
config/constants/development.js
config/constants/production.js
package-lock.json
package.json
src/routes.js
src/styles/modal.module.scss

* logout user automatically if they've been idle for a configured duration

Jira vuln 2333

---

src/components/ChallengesComponent/ChallengeList/ChallengeList.module.scss
src/components/ChallengesComponent/ChallengeList/index.js

https://github.com/topcoder-platform/work-manager/issues/1407

Billing account tab switching fix

---

src/actions/challenges.js
src/components/ChallengesComponent/ChallengeList/index.js
src/containers/Challenges/index.js

Hotfix for https://topcoder.atlassian.net/browse/PROD-4083

Filter challenges by logged in user

---

src/actions/challenges.js

https://topcoder.atlassian.net/browse/PROD-4198

Release 0.20.5

---

src/actions/challenges.js
src/components/ChallengeEditor/ChallengeSchedule-Field/index.js
src/components/ChallengeEditor/index.js
src/components/ChallengesComponent/ChallengeList/index.js
src/components/DurationInput/DurationInput.module.scss
src/components/DurationInput/index.js
src/components/PhaseInput/PhaseInput.module.scss
src/components/PhaseInput/index.js
src/components/StartDateInput/index.js
src/containers/Challenges/index.js
src/util/date.js
src/util/phase.js

https://topcoder.atlassian.net/browse/PROD-3400

PROD - changes to date editing on a project

---

config/constants/development.js
config/constants/production.js
src/actions/challenges.js
src/components/ChallengesComponent/ChallengeList/index.js
src/components/SelectUserAutocomplete/index.js
src/components/Tab/index.js
src/containers/Challenges/index.js
src/containers/Tab/index.js
src/services/user.js

https://topcoder.atlassian.net/browse/PROD-4215
https://topcoder.atlassian.net/browse/PROD-4222

Release 0.20.6

---

src/routes.js
src/util/tc.js

https://github.com/topcoder-platform/work-manager/issues/1527
https://topcoder.atlassian.net/browse/PROD-4262

Redirect fix

---

.circleci/config.yml
src/components/ChallengeEditor/ChallengeViewTabs/index.js
src/components/ChallengeEditor/Submissions/index.js

https://topcoder.atlassian.net/browse/PROD-4266
https://topcoder.atlassian.net/browse/PROD-4274
https://topcoder.atlassian.net/browse/PROD-4289
https://topcoder.atlassian.net/browse/PROD-4274

Release 0.20.9

---

src/actions/challenges.js
src/components/ChallengeEditor/ChallengeViewTabs/index.js
src/components/ChallengeEditor/Registrants/Registrants.module.scss
src/components/ChallengeEditor/Registrants/index.js
src/components/ChallengeEditor/Submissions/Submissions.module.scss
src/components/ChallengeEditor/Submissions/index.js
src/config/constants.js
src/services/user.js
src/util/tc.js

https://topcoder.atlassian.net/browse/PROD-4266
https://topcoder.atlassian.net/browse/PROD-4278
https://topcoder.atlassian.net/browse/PROD-4282
https://topcoder.atlassian.net/browse/PROD-4283
https://topcoder.atlassian.net/browse/PROD-4284
https://topcoder.atlassian.net/browse/PROD-4269

PROD --> v20.10

---

src/actions/challenges.js
src/components/ChallengeEditor/index.js

https://topcoder.atlassian.net/browse/PROD-4413
https://topcoder.atlassian.net/browse/PROD-4379
https://topcoder.atlassian.net/browse/PROD-4327

Fix bug where copilots can't assign tasks to themselves, even before activation

---

src/components/ChallengeEditor/index.js

https://topcoder.atlassian.net/browse/PS-263

Switch how we save the challenge (PS-263)

---

docker/Dockerfile
test-automation/Dockerfile

- Instead of running docker with root user, created a user and provided the user with permission only for the work directory, this way this will/might fix default user privilege issue

PM-219: default user privilege

---

src/routes.js

- Used encodeURIComponent in the url to avoid xss

PM-217: poor validation cross site scripting

---

test-automation/config/config.json

- Removed the password from config json. This was decided in standup.

PM-223: removed password from config json

---

config/constants/development.js
config/constants/production.js

- added https to nav url as without it is breaking url constructor

fix: added https to nav url as without it is breaking url constructor

---

src/containers/TaaSProjectForm/index.js
src/util/validation.js

https://topcoder.atlassian.net/browse/PM-684
Makes the job description field required

PM-684 - make job description a required field for Taas Projects

---

src/containers/TaaSProjectForm/index.js
src/util/validation.js

PM-683 - update "workload" field to "workLoad"

PM-683 - update workload field

---

src/containers/TaaSProjectForm/index.js

https://topcoder.atlassian.net/browse/PM-683

PM-683 - send jobid on update for taas projects

---

src/actions/challenges.js

On the landing, limit the challenges to only "mine" for non-admin users

PM-858 - limit challenges list

---

.circleci/config.yml
src/actions/sidebar.js
src/components/ChallengesComponent/ChallengeList/index.js
src/components/ChallengesComponent/index.js
src/components/Select/index.js
src/containers/Challenges/index.js
src/reducers/sidebar.js

https://topcoder.atlassian.net/browse/PM-902 - load more projects when scrolling in the projects dropdown

PM-902 - load more projects on dropdown scroll

---

.circleci/config.yml
src/components/UserCard/index.js

- show invite handle if email doesn't exist in invite

fix(PM-1077): show invite handle if email doesn't exist in invite

---

src/containers/ProjectInvitations/index.js

- show error when invite comes from an closed opportunity
Ticket link - https://topcoder.atlassian.net/browse/PM-1398

fix(PM-1398): show error when invite comes from an closed opportunity

---

src/components/ChallengeEditor/ChallengeView/index.js

Adds the link to the Community App Challenge details page, in Work Manager challenge view page

PM-1349 Add CA challenge details link to WM
